# Generated by Django 5.2.3 on 2025-06-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('speciality', models.CharField(choices=[('Nephrologist', 'Nephrologist'), ('Cardiologist', 'Cardiologist'), ('Dentist', 'Dentist'), ('Orthopedic', 'Orthopedic'), ('Dermatologist', 'Dermatologist')], max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('doctor', models.ManyToManyField(related_name='patients', to='Patient.doctor')),
            ],
        ),
    ]
